# Generated by Django 4.1.2 on 2022-10-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_place_description_place_tf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
